"""обавление song_index к Character

Revision ID: 11308e5078c8
Revises: 3f161242a8f9
Create Date: 2024-05-22 23:11:08.873938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11308e5078c8'
down_revision = '3f161242a8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('song_index')

    # ### end Alembic commands ###
