"""обавление attack_needed к Character

Revision ID: f6cc8ce1c87c
Revises: 11308e5078c8
Create Date: 2024-05-22 23:40:45.237472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cc8ce1c87c'
down_revision = '11308e5078c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attacks_needed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('attacks_needed')

    # ### end Alembic commands ###
